### ISSUE TITLE
Not able to get the generator work

### ISSUE THREAD

**Issue by sanjusoftware** [charlotte-ruby/impressionist#109]
Hi,

I added the gem in the gemfile and now I am trying to run the generator to and I get the following error:

rails g impressionist

/Users/sanjeevmishra/.rvm/gems/ree-1.8.7-2012.02/gems/bundler-1.2.2/lib/bundler/runtime.rb:197: warning: Insecure world writable dir /usr/local in PATH, mode 040777
/Users/sanjeevmishra/.rvm/gems/ree-1.8.7-2012.02/gems/bundler-1.2.2/lib/bundler/runtime.rb:197: warning: Insecure world writable dir /usr/local in PATH, mode 040777
/Users/sanjeevmishra/.rvm/gems/ree-1.8.7-2012.02/gems/impressionist-1.4.0/lib/impressionist/load.rb:5:in `require': /Users/sanjeevmishra/.rvm/gems/ree-1.8.7-2012.02/gems/impressionist-1.4.0/lib/impressionist/counter_cache.rb:46: syntax error, unexpected ')', expecting '=' (SyntaxError)
/Users/sanjeevmishra/.rvm/gems/ree-1.8.7-2012.02/gems/impressionist-1.4.0/lib/impressionist/counter_cache.rb:83: syntax error, unexpected kEND, expecting $end
    from /Users/sanjeevmishra/.rvm/gems/ree-1.8.7-2012.02/gems/impressionist-1.4.0/lib/impressionist/load.rb:5
    from /Users/sanjeevmishra/.rvm/gems/ree-1.8.7-2012.02/gems/impressionist-1.4.0/lib/impressionist.rb:1:in`require'
    from /Users/sanjeevmishra/.rvm/gems/ree-1.8.7-2012.02/gems/impressionist-1.4.0/lib/impressionist.rb:1
    from /Users/sanjeevmishra/.rvm/gems/ree-1.8.7-2012.02/gems/bundler-1.2.2/lib/bundler/runtime.rb:68:in `require'
    from /Users/sanjeevmishra/.rvm/gems/ree-1.8.7-2012.02/gems/bundler-1.2.2/lib/bundler/runtime.rb:68:in`require'
    from /Users/sanjeevmishra/.rvm/gems/ree-1.8.7-2012.02/gems/bundler-1.2.2/lib/bundler/runtime.rb:66:in `each'
    from /Users/sanjeevmishra/.rvm/gems/ree-1.8.7-2012.02/gems/bundler-1.2.2/lib/bundler/runtime.rb:66:in`require'
    from /Users/sanjeevmishra/.rvm/gems/ree-1.8.7-2012.02/gems/bundler-1.2.2/lib/bundler/runtime.rb:55:in `each'
    from /Users/sanjeevmishra/.rvm/gems/ree-1.8.7-2012.02/gems/bundler-1.2.2/lib/bundler/runtime.rb:55:in`require'
    from /Users/sanjeevmishra/.rvm/gems/ree-1.8.7-2012.02/gems/bundler-1.2.2/lib/bundler.rb:128:in `require'
    from /Users/sanjeevmishra/projects/alumnicenter2/config/application.rb:105
    from /Users/sanjeevmishra/.rvm/gems/ree-1.8.7-2012.02/gems/railties-3.1.12/lib/rails/commands.rb:21:in`require'
    from /Users/sanjeevmishra/.rvm/gems/ree-1.8.7-2012.02/gems/railties-3.1.12/lib/rails/commands.rb:21
    from script/rails:6:in `require'
    from script/rails:6

Can you please help why I am getting this error. As you can see that I am on ree-1.8.7 and using rails 3.1.12

**Comment by jgrau** [comment]
Closing as stale
