### ISSUE TITLE
How do you get the count for action impressions?

### ISSUE THREAD

**Issue by peteykun** [charlotte-ruby/impressionist#143]
The blurb for impressionist says that '[it] can log page impressions (technically action impressions)', however, as far as I can see, the only way to get impressions_count is through a model instance. However, I wish to count the impressions on the `index` action, so it will not be possible to associate it with an instance of a model. Is there any way to do this? (One of the examples includes `:index` as an impressionist action, so I guess there's something I'm missing...?)

**Comment by brendonrapp** [comment]
This belongs in the README somewhere. Shouldn't have to search the issue tracker for this answer.
