### ISSUE TITLE
prevent deleting all impressions records if item soft deleted

### ISSUE THREAD

**Issue by rkrayovskyy** [charlotte-ruby/impressionist#193]
Hi,

I use paranoia gem for soft deleting items, which are also impressionable.
When I soft delete an item, all impression count records are destroyed.

Is there a way to prevent such behaviour?

thanks,
R

**Comment by kashifnaseer** [comment]
I'm also facing same issue. @rkrayovskyy did you find any solution for this ?

**Comment by jgrau** [comment]
Hmm. Good question. In v1.6.0 the `dependent: :destroy` has been changed to `dependent: :delete_all`. Could you check if you still have the issue? If you do then please reopen this issue and if you're up for it submit a PR. Yay! :)
