### ISSUE TITLE
Not able to record anything other than impressionable id and type.

### ISSUE THREAD

**Issue by kumar12** [charlotte-ruby/impressionist#194]
I'm using Impressionist gem in my 2 projects with Rails 4.1.8 and Ruby 2.1.2 and having this problem in both. 

In the model:
is_impressionable :counter_cache => true

in the controller show method:
impressionist(@post)   ## post being the model 

Also, as User id is not getting captured, //@post.impressionist_count is  always returning 0 however //@post.impressions.count is returning count of all the records. 

Any known issues out there or am I missing something?

**Comment by jgrau** [comment]
@kumar12 have you added the column to hold the counter cache? https://github.com/charlotte-ruby/impressionist#adding-column-to-model

This is core functionality of the gem and it works for a lot of people so I presume it's something in your application. If this is still an issue for you please post some more code and I'll see if I can help.
