### ISSUE TITLE
Missing params field in migration

### ISSUE THREAD

**Issue by sjayanna** [charlotte-ruby/impressionist#196]
Version 1.5.1

See attached screenshot
<img width="911" alt="screen shot 2015-07-26 at 10 57 11 am" src="https://cloud.githubusercontent.com/assets/194508/8894458/1ce4e416-3385-11e5-875d-7e99effc8f23.png">

**Comment by kpheasey** [comment]
@sjayanna The version from rubygems does not have support for capturing params.  You need to use the github source.

```
gem 'impressionist', git: 'git@github.com:charlotte-ruby/impressionist.git'
```

If you have already run the migration from the rubygems version, then you will need to create a new migration with the following

```ruby
class AddParamsToImpressions < ActiveRecord::Migration
  def change
    add_column :impressions, :params, :text
    add_index :impressions, [:impressionable_type, :impressionable_id, :params], :name => 'poly_params_request_index', :unique => false
  end
end
```

**Comment by jgrau** [comment]
@kpheasey thanks for describing your solution! I've made an [upgrade guide](https://github.com/charlotte-ruby/impressionist/blob/master/UPGRADE_GUIDE.md) that describes this as well.
