### ISSUE TITLE
Any performance issues?

### ISSUE THREAD

**Issue by sjayanna** [charlotte-ruby/impressionist#197]
Hey all,
Are there any performance issues using this amazing gem? It is working perfectly fine giving us the count on the number of views of our models but just concerned if it is making our database grow too much?

Any insight will be helpful.
Thanks!

**Comment by mika-cn** [comment]
it will slow

**Comment by bondanherumurti** [comment]
i have problem when integrate the is_impressionable model to active_admin, because every time we want to load the all model list, it will execute 

Impression Load (104.2ms)  SELECT `impressions`.* FROM `impressions`

and with tons of data, this query will kill your memory

**Comment by jgrau** [comment]
@sjayanna databases are build to hold large amounts of data. Adding a record for every view of a model will get you a large database but in my experience it will not slow you app.

@bondanherumurti yes I had the same issue. I solved it by using `remove_filter :impressions`
