### ISSUE TITLE
How to track views of current_admin?

### ISSUE THREAD

**Issue by rdudacz** [charlotte-ruby/impressionist#199]
Hi there,

I am using this gem for a while and it works flawlessly for users.
Now I face a situation when is needed to track activity of admins (I am using `Devise` and a standalone model for admins - current admin is held in `current_admin`).

How to track admins?
I found this - https://github.com/3dd13/impressionist - but it didn't help me, it leaves `NULL` in the `user_id` column.
Is there a way to add a new column `admin_id` and store there the `current_admin.id` information? Or is there even a better way yet?

Thank you, have a good weekend!
Radek

**Comment by jgrau** [comment]
Hi @rdudacz. Saving the `user_id` of the `current_user` is current the only thing supported. I gave the fork you link to a quick look and I would love to add functionality like that if you're up for making a PR. I'll close this issue but PR is welcome!
