### ISSUE TITLE
Clearing impressions

### ISSUE THREAD

**Issue by acetinick** [charlotte-ruby/impressionist#201]
I have some websites generating quite a lot of traffic and have been using this gem to track impressions, due to the ease of use and handling of robot traffic.  

Although the gem works great, my database has been getting massive due to the size of the impressions table and it's data that I don't care about after a week or so.

I have tried building cleanup scripts to delete old impressions from the impressions table but on the next impression it will just reset the impression count on the model.

Is there any solution to this?

**Comment by sjayanna** [comment]
@acetinick I don't think so. I think the newer version will have this, but not sure when it will be released.

**Comment by jgrau** [comment]
Currently there's no solution. The counter cache re-counts the impressions so removing impression records will not work. Is the database size your problem or is it queries that starts to become slow? I would suspect with proper indexes that the latter is solvable.

Reopen this if there's anything more I can do on this.
