### ISSUE TITLE
undefined method `impressionist_counter_caching?' for Message:Class

### ISSUE THREAD

**Issue by tothestar** [charlotte-ruby/impressionist#203]
Hi,
    i custom a class called Message and put it in the lib directory. then required it in my controller. then i get the error like this:

undefined method `impressionist_counter_caching?' for Message:Class

Extracted source (around line #52):

```
  def counter_caching?
    impressionable_class.
      impressionist_counter_caching?
  end
```

**Comment by jgrau** [comment]
Are you overriding an active record class also named `Message`? Or have you added `is_impressionable` to your `Message` class in `lib`. The latter won't work as this is for `ActiveRecord` classes, not POROs. Reopen if this does not fix your problem :)
