### ISSUE TITLE
Impressionist with mongoid

### ISSUE THREAD

**Issue by BorisBresciani** [charlotte-ruby/impressionist#206]
Hello,

When I execute the following command:
rails g impressionist --orm mongoid

I have this error:
gems/ruby-2.2.1/gems/impressionist-1.5.1/lib/impressionist/models/active_record/impression.rb:5:in `<top (required)>': uninitialized constant ActiveRecord (NameError)

Thank you for your help ! Good day

**Comment by ibnutoriq** [comment]
create file config/initializers/impression.rb and add 
Impressionist.orm = :mongoid
then try execute rails g impressionist --orm mongoid again.

**Comment by jgrau** [comment]
The solution provided by @ibnutoriq is the official one. Is that working? Reopen if it doesn't :)

**Comment by x1wins** [comment]
i have same problem with rails 6, mongoid
@ibnutoriq your solution is working well
