### ISSUE TITLE
Is there any way to get the GeoLocation with impressions

### ISSUE THREAD

**Issue by kashifnaseer** [charlotte-ruby/impressionist#207]
Is there any way to get the GeoLocation of the User with impressions ? Currently, it is only storing the IP address, i want to store the physical address of the user for which we are creating impressions.

**Comment by johnmcaliley** [comment]
You would have to do this after the fact.  Maybe add a background process that does the IP to Geo conversion using a 3rd party service.  This is not something that would be efficient or reliable enough to add directly to this gem.
