### ISSUE TITLE
Is it still maintained at all? 

### ISSUE THREAD

**Issue by AndreiMotinga** [charlotte-ruby/impressionist#211]

**Comment by rposborne** [comment]
Maintainers, What can we do to help?

**Comment by johnmcaliley** [comment]
sorry guys, I have totally dropped the ball on this repo and haven't been looking at issues for the last 6 months.  I'm just now getting around to merging in some of the rails 5 stuff.  I have handed it off to a few other maintainers over the years, but none of them are actively maintaining it either.  I'm willing to give admin access to this and access to the rubygems account for anyone that is interested in maintaining.

**Comment by AndreiMotinga** [comment]
@johnmcaliley,  you should probably update readme, to let people know

**Comment by rposborne** [comment]
@johnmcaliley I can certainly be a gem "gardener", wouldn't be able to add much of raw dev resources but can certain help out.

**Comment by rposborne** [comment]
@johnmcaliley bump.

**Comment by AndreiMotinga** [comment]
@rposborne what does bump mean ?

**Comment by rposborne** [comment]
@AndreiMotinga it's English slang, commonly used to trigger a new notification on a topic that still requires attention.   In this case, attempting to get @johnmcaliley attention, showing that I am here and willing to help out.   

(also thanks for asking)

**Comment by AndreiMotinga** [comment]
@rposborne, thanks for the clarification. good to know ;)

**Comment by jgrau** [comment]
I've taken over the role as maintainer but I'd love a sidekick. Please let me know if you're interested :)
