### ISSUE TITLE
Rails 5 Deprecation warning - before_filter

### ISSUE THREAD

**Issue by shadowed87** [charlotte-ruby/impressionist#214]
After upgrading to Rails 5 I am receiving the following deprecation warning:

`
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 
5.1. Use before_action instead. (called from included at /home/shad/.bundle/ruby/2.3.0/impressionist-6e551927ec29/app/controllers/impressionist_controller.rb:12)
`

**Comment by rchrand** [comment]
#241 fixes this, closing
