### ISSUE TITLE
Feature Request: Has this been tested with Dynamoid?

### ISSUE THREAD

**Issue by mmhan** [charlotte-ruby/impressionist#217]
Just wondering if this has been tested with [Dynamoid](https://github.com/Dynamoid/Dynamoid), as I was trying to use it with that.

Is that in the roadmap?

**Comment by johnmcaliley** [comment]
we don't have a roadmap at this point and no one is really actively maintaining it.  I'm looking for volunteers to take it over right now.

**Comment by jgrau** [comment]
Support for dynamoid is not in the roadmap but a PR for supporting dynamoid would be more than welcome!
