### ISSUE TITLE
Impressionist 1.5.2 was broken

### ISSUE THREAD

**Issue by dostapn** [charlotte-ruby/impressionist#220]
After update gem from 1.5.1 to 1.5.2 app was broke 
`'ActiveRecord::UnknownAttributeError - unknown attribute 'params' for Impression.:
  activerecord (4.2.3) lib/active_record/attribute_assignment.rb:59:in 'rescue in _assign_attribute'
  activerecord (4.2.3) lib/active_record/attribute_assignment.rb:54:in '_assign_attribute'
activerecord (4.2.3) lib/active_record/attribute_assignment.rb:65:in 'block in assign_nested_parameter_attributes'
  activerecord (4.2.3) lib/active_record/attribute_assignment.rb:65:in 'assign_nested_parameter_attributes'
  activerecord (4.2.3) lib/active_record/attribute_assignment.rb:45:in 'assign_attributes'
  activerecord (4.2.3) lib/active_record/core.rb:564:in 'init_attributes'
activerecord (4.2.3) lib/active_record/core.rb:281:in 'initialize'
  activerecord (4.2.3) lib/active_record/inheritance.rb:61:in 'new'
  activerecord (4.2.3) lib/active_record/persistence.rb:33:in 'create'
/Users/dostapn/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/impressionist-1.5.2/app/controllers/impressionist_controller.rb:37:in 'impressionist_subapp_filter'
  /Users/dostapn/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/impressionist-1.5.2/app/controllers/impressionist_controller.rb:6:in 'block in impressionist'
  activesupport (4.2.3) lib/active_support/callbacks.rb:446:in 'block in make_lambda'
activesupport (4.2.3) lib/active_support/callbacks.rb:162:in 'block in halting'
  activesupport (4.2.3) lib/active_support/callbacks.rb:502:in 'block in call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:502:in 'call'
activesupport (4.2.3) lib/active_support/callbacks.rb:496:in 'block (2 levels) in around'
  activesupport (4.2.3) lib/active_support/callbacks.rb:290:in 'block (2 levels) in halting_and_conditional'
  app/controllers/application_controller.rb:84:in 'scope_current_oktmo'
activesupport (4.2.3) lib/active_support/callbacks.rb:430:in 'block in make_lambda'
  activesupport (4.2.3) lib/active_support/callbacks.rb:289:in 'block in halting_and_conditional'
  activesupport (4.2.3) lib/active_support/callbacks.rb:495:in 'block in around'
activesupport (4.2.3) lib/active_support/callbacks.rb:503:in 'call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:88:in 'run_callbacks'
  actionpack (4.2.3) lib/abstract_controller/callbacks.rb:19:in 'process_action'
actionpack (4.2.3) lib/action_controller/metal/rescue.rb:29:in 'process_action'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:32:in 'block in process_action'
  activesupport (4.2.3) lib/active_support/notifications.rb:164:in 'block in instrument'
activesupport (4.2.3) lib/active_support/notifications/instrumenter.rb:20:in 'instrument'
  activesupport (4.2.3) lib/active_support/notifications.rb:164:in 'instrument'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:30:in 'process_action'
actionpack (4.2.3) lib/action_controller/metal/params_wrapper.rb:250:in 'process_action'
  activerecord (4.2.3) lib/active_record/railties/controller_runtime.rb:18:in 'process_action'
  actionpack (4.2.3) lib/abstract_controller/base.rb:137:in 'process'
actionview (4.2.3) lib/action_view/rendering.rb:30:in 'process'
  actionpack (4.2.3) lib/action_controller/metal.rb:196:in 'dispatch'
  actionpack (4.2.3) lib/action_controller/metal/rack_delegation.rb:13:in 'dispatch'
actionpack (4.2.3) lib/action_controller/metal.rb:237:in 'block in action'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:76:in 'dispatch'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:45:in 'serve'
actionpack (4.2.3) lib/action_dispatch/routing/mapper.rb:49:in 'serve'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:43:in 'block in serve'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in 'serve'
actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:821:in 'call'
   () Users/dostapn/.rvm/gems/ruby-2.2.1@global/gems/bullet-5.4.0/lib/bullet/rack.rb:10:in 'call'
  devise_cas_authenticatable (1.7.1) lib/devise_cas_authenticatable/single_sign_out/rack.rb:14:in 'call'
warden (1.2.6) lib/warden/manager.rb:35:in 'block in call'
  warden (1.2.6) lib/warden/manager.rb:34:in 'call'
  rack (1.6.4) lib/rack/etag.rb:24:in 'call'
rack (1.6.4) lib/rack/conditionalget.rb:38:in 'call'
  rack (1.6.4) lib/rack/head.rb:13:in 'call'
  actionpack (4.2.3) lib/action_dispatch/middleware/params_parser.rb:27:in 'call'
actionpack (4.2.3) lib/action_dispatch/middleware/flash.rb:260:in 'call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in 'context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in 'call'
actionpack (4.2.3) lib/action_dispatch/middleware/cookies.rb:560:in 'call'
  activerecord (4.2.3) lib/active_record/query_cache.rb:36:in 'call'
  activerecord (4.2.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in 'call'
activerecord (4.2.3) lib/active_record/migration.rb:377:in 'call'
  actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:29:in 'block in call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:84:in 'run_callbacks'
actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:27:in 'call'
  actionpack (4.2.3) lib/action_dispatch/middleware/reloader.rb:73:in 'call'
  actionpack (4.2.3) lib/action_dispatch/middleware/remote_ip.rb:78:in 'call'
better_errors (2.1.1) lib/better_errors/middleware.rb:84:in 'protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in 'better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in 'call'
actionpack (4.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:17:in 'call'
  actionpack (4.2.3) lib/action_dispatch/middleware/show_exceptions.rb:30:in 'call'
  railties (4.2.3) lib/rails/rack/logger.rb:38:in 'call_app'
railties (4.2.3) lib/rails/rack/logger.rb:20:in 'block in call'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in 'block in tagged'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:26:in 'tagged'
activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in 'tagged'
  railties (4.2.3) lib/rails/rack/logger.rb:20:in 'call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in 'call_with_quiet_assets'
request_store (1.3.1) lib/request_store/middleware.rb:9:in 'call'
  actionpack (4.2.3) lib/action_dispatch/middleware/request_id.rb:21:in 'call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in 'call'
rack (1.6.4) lib/rack/runtime.rb:18:in 'call'
  activesupport (4.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in 'call'
  rack (1.6.4) lib/rack/lock.rb:17:in 'call'
actionpack (4.2.3) lib/action_dispatch/middleware/static.rb:116:in 'call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in 'call'
  railties (4.2.3) lib/rails/engine.rb:518:in 'call'
railties (4.2.3) lib/rails/application.rb:165:in 'call'
  rack (1.6.4) lib/rack/content_length.rb:15:in 'call'
  thin (1.7.0) lib/thin/connection.rb:86:in 'block in pre_process'
thin (1.7.0) lib/thin/connection.rb:84:in 'pre_process'
  thin (1.7.0) lib/thin/connection.rb:53:in 'process'
  thin (1.7.0) lib/thin/connection.rb:39:in 'receive_data'
eventmachine (1.2.0.1) lib/eventmachine.rb:194:in 'run'
  thin (1.7.0) lib/thin/backends/base.rb:73:in 'start'
  thin (1.7.0) lib/thin/server.rb:162:in 'start'
rack (1.6.4) lib/rack/handler/thin.rb:19:in 'run'
  rack (1.6.4) lib/rack/server.rb:286:in 'start'
  railties (4.2.3) lib/rails/commands/server.rb:80:in 'start'
railties (4.2.3) lib/rails/commands/commands_tasks.rb:80:in 'block in server'
  railties (4.2.3) lib/rails/commands/commands_tasks.rb:75:in 'server'
  railties (4.2.3) lib/rails/commands/commands_tasks.rb:39:in 'run_command!'
railties (4.2.3) lib/rails/commands.rb:17:in '<top (required)>'
  bin/rails:8:in '<top (required)>'
  spring (1.7.2) lib/spring/client/rails.rb:28:in 'call'
spring (1.7.2) lib/spring/client/command.rb:7:in 'call'
  spring (1.7.2) lib/spring/client.rb:30:in 'run'
  spring (1.7.2) bin/spring:49:in '<top (required)>'
spring (1.7.2) lib/spring/binstub.rb:11:in '<top (required)>'
  bin/spring:13:in '<top (required)>'
  bin/rails:3:in '<main>'`

**Comment by johnmcaliley** [comment]
One of the pull requests I merged added a new column, but the migration file was not added, so if you upgrade, the Impression model references this column, but it will not exist in your database until you add a migration for it.  My recommendation is to create a new migration and add this code to create the new column/index.  The other alternative is to specify version "1.5.1" in your gemfile so that you are loading the previous version.

```
add_column :impressions, :params, :text

add_index :impressions, [:impressionable_type, :impressionable_id, :params], :name => "poly_params_request_index", :unique => false
```

**Comment by samroberts93** [comment]
Same Problem, I just downgraded to 1.5.1

**Comment by majtymit** [comment]
+1

**Comment by hopewise** [comment]
+1

**Comment by el-fudo** [comment]
+1

**Comment by jgrau** [comment]
I've added an upgrade guide which explains this

https://github.com/charlotte-ruby/impressionist/blob/master/UPGRADE_GUIDE.md

**Comment by vanbumi** [comment]
which command for that migration ? can you specify it please?
