### ISSUE TITLE
BLOB/TEXT column 'params' used in key specification without a key length: CREATE  INDEX `poly_params_request_index`  ON `impressions` (`impressionable_type`, `impressionable_id`, `params`)

### ISSUE THREAD

**Issue by sethukarthik** [charlotte-ruby/impressionist#222]
I ma using MySQL database for my application. When am trying to migration am getting following issue.

BLOB/TEXT column 'params' used in key specification without a key length: CREATE  INDEX `poly_params_request_index`  ON `impressions` (`impressionable_type`, `impressionable_id`, `params`)

So i have added length to params index and then now it is working.

add_index :impressions, [:impressionable_type, :impressionable_id, :params], :name => "poly_params_request_index", :unique => false, :length => {:params => 255 }

Please let me know what i have did i correct or i need to change anything else.

**Comment by 1v** [comment]
Same.

**Comment by barbarafux** [comment]
I have the same problem with MySQL.

**Comment by dancinglightning** [comment]
same, using 
mysql2 (0.4.5)
rails (5.0.0.1)
ruby 2.3.1p112

solution above works though
