### ISSUE TITLE
Can i use mongoid without change the activerecord postgresql?

### ISSUE THREAD

**Issue by muratbsts** [charlotte-ruby/impressionist#229]
Hello, thanks for great gem.
I've using postgresql as activerecord orm. I want to use mongoid with impressionist. Is it possible?

Maybe duplicate question with https://github.com/charlotte-ruby/impressionist/issues/112

**Comment by muratbsts** [comment]
Is project dead? 🙁

**Comment by jgrau** [comment]
Hi @muratbsts 

The project has been dead but I'm trying to resurrect it. I'm not super familiar with the codebase yet and haven't needed to use mongoid so I can't answer your question. I can refer you to the readme https://github.com/charlotte-ruby/impressionist#are-you-using-mongoid - have you tried that?

**Comment by muratbsts** [comment]
Hey @jgrau, thanks for reply. I tried using --orm mongoid option at another project. It works. But I want to use mongoid with postgres. I think this is not possible yet. Maybe I can use ahoy gem as alternative.

Whatever... If you need to help for resurrection I can.

Thanks again... ✋

**Comment by jgrau** [comment]
> I want to use mongoid with postgres

You mean you want to have both mongoid with mongodb and active record with postgresql running at the same time, right? I would expect that is exactly what is possible using the example from the readme.

I would love help for resurrection. The best help is picking issues off the issues list and making pull requests :)

**Comment by muratbsts** [comment]
Yep. It's right. I want to use both mongoid(for only impressionist) and postgresql as  activerecord orm. I'll using impressionist for helping you. God bless you. :slightly_smiling_face:
