### ISSUE TITLE
rollback transaction after every action

### ISSUE THREAD

**Issue by cdfa** [charlotte-ruby/impressionist#257]
I just set up impressionist in a fresh rails project, but no impressions get written to the database. There is a 'rollback transaction'  in the logs, which i'm quite certain comes from impressionist, because when i remove the impressionist call in my controller and is_impressionable in the model it doesn't show up anymore. I can't find out what the problem is though, because there are no further details on why there was a rollback in the logs and Impression.errors doesn't exist apparently.

Any help would be greatly appreciated.

**Comment by martijncasteel** [comment]
A rollback can be dangerous, often the transaction intended is also rolled back.

**Comment by cdfa** [comment]
The actual transaction doesn't get rolled back. Below are the logs
Started POST "/test" for 127.0.0.1 at 2017-10-31 14:02:04 +0100
Processing by TestController#create as */*
  Parameters: {"test"=>"test", "authenticity_token"=>"vQ2yIxzv7HX/Nz2rNf86qFqj3KFLvM9jhhB1GTxkFd3riFLgS5mzyZ8l6oRCokLU7ruvwYqZGmCShWrcAOPzmA=="}
   (0.1ms)  begin transaction
   (0.0ms)  rollback transaction
   (0.1ms)  begin transaction
  SQL (0.2ms)  INSERT INTO "tests" ("test", "created_at", "updated_at") VALUES (?, ?, ?)  [["test", "test"], ["created_at", "2017-10-31 13:02:04.771126"], ["updated_at", "2017-10-31 13:02:04.771126"]]
   (26.1ms)  commit transaction
  Rendering test/create.html.erb within layouts/application
  Rendered test/create.html.erb within layouts/application (0.3ms)
Completed 200 OK in 63ms (Views: 14.3ms | ActiveRecord: 27.3ms)

Weirdly, I also get a rollback after the index method:
Started GET "/test" for 127.0.0.1 at 2017-10-31 14:07:32 +0100
   (0.1ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by TestController#index as HTML
   (0.1ms)  begin transaction
   (0.1ms)  rollback transaction
  Rendering test/index.html.erb within layouts/application
  Rendered test/index.html.erb within layouts/application (0.6ms)
Completed 200 OK in 178ms (Views: 127.6ms | ActiveRecord: 0.7ms)

**Comment by ThreeWest** [comment]
I have this same issue using Ruby 2.4.0, the latest version of the impressionist gem and the latest version of Rails. I don't have this issue on my older apps.

**Comment by Senegal** [comment]
hi @ThreeWest ,

> OK, this rollback happens when using Impressionist on controllers that are not linked to a model.

how it can be fixed?

**Comment by ThreeWest** [comment]
Hi @Senegal 

I have no idea. I had no choice but to remove the gem.  I'm not sure what's going on with it. When I get some time, I'll try to add it back.

**Comment by neerajkumar** [comment]
Seems, its not compatible with latest version of ruby and rails.

**Comment by johnmcaliley** [comment]
this should be fixed in the latest release v1.6.1

**Comment by tkimana** [comment]
How Could I fix it because it's not working with the latest version release
