### ISSUE TITLE
Using 'impressionist' controller mixin without an associated model

### ISSUE THREAD

**Issue by okeefm** [charlotte-ruby/impressionist#260]
I'm trying to add the `impressionist` mixin into a controller I've got in Rails 5.1, but I'm running into an issue. The controller doesn't have a model associated with it, so the Impression won't save, with the validation error `ActiveRecord::RecordInvalid: Validation failed: Impressionable must exist`.

**Comment by johnmcaliley** [comment]
should be fixed in v1.6.1
