### ISSUE TITLE
Rack session id is no longer allow to be coerced to string

### ISSUE THREAD

**Issue by naemcivic** [charlotte-ruby/impressionist#281]
ISSUE:
Update to rack prevents session id to coerce into a string
Please find changes here:
https://github.com/rack/rack/commit/cc1d162d28396b6a71f266e6a40ffc19a258792b#diff-681da9662953fa2d37d188d52d1acfaeR31

We are trying to store this into a string on impressions.session_hash which will try to convert it into string before storing.

**Comment by tatums** [comment]
@naemcivic Thanks for that info! The referenced issue lead me to a fix. I was using rack 2.0.8 and upgrading 2.1.x fixed it. :pray:

**Comment by invalidusrname** [comment]
Looks like this issue have been solved. Closing this one out
