### ISSUE TITLE
Support different user_scope. not only current_user

### ISSUE THREAD

**Issue by 3dd13** [charlotte-ruby/impressionist#84]
### add an option to support other user scope

I made some changes on my branch to draft the changes, but haven't finalized yet:
https://github.com/3dd13/impressionist
#### Changes on my branch
1. took away attr_accessible to make it runnable on rails4
2. added user_scope option to enable other user scope instead of only current_user
3. added user_type to impression model to maintain the polymorphic user relationship
#### Note
1. I didn't add tests for these changes.
2. I didn't make the changes for MongoDB, only updated the ActiveRecord stuff

**Comment by jgrau** [comment]
Feel free to open a PR but for now I'll close this.
