### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by Linuus** [charlotte-ruby/impressionist#94]
Hi

I have had impressionist running for a while and the impressions table is currently at about 220.000 rows. This has made my site pretty slow.

Do you have any tips on how to increase the performance? I have all the default indexes as well as the counter cache.
I guess it could be that I'm only recording unique  impressions so it has to look through the database records before creating a new impression...

How do you handle these issues?

I'm running on Heroku using Postgres.

For instance, queries like this isn't very funny:

```
 (13684.8ms)  SELECT DISTINCT COUNT(DISTINCT "impressions"."request_hash") FROM "impressions" WHERE "impressions"."impressionable_id" = $1 AND "impressions"."impressionable_type" = $2  [["impressionable_id", 60], ["impressionable_type", "Artist"]]
```

This was on my local machine (which is a bit slow) but anyway....

**Comment by Premanandh-S** [comment]
test

**Comment by AlejandroFernandesAntunes** [comment]
As a workaround for it; I've made a backup model, basically copying the impressions model (adding an extra column for the original id) and moved there all the registries from before 4 months ago using a rake task. That helped a lot and maintained the overall functionallity over the site.
