### ISSUE TITLE
Not working with mongoid

### ISSUE THREAD

**Issue by regdog** [charlotte-ruby/impressionist#96]
After the gem installed, I added the impression.rb manually and set the config.orm to mongoid. But it still load the ActiveRecord Models. So it reports error, "uninitialized constant ActiveRecord (NameError)".

The command "rails g impressionist --orm mongoid" fails as the same.

Is it a bug?

**Comment by emilenriquez** [comment]
I also have same situation with @regdog

**Comment by emilenriquez** [comment]
does this  work for mongoid users? @acnalesso
